srun run.py -s my_benchmarks -a 5p-stencil -b flux -d s1 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil -b flux -d s2 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil -b flux -d s3 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil -b flux -d s4 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil -b flux -d s5 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil_opt -b flux -d s1 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil_opt -b flux -d s2 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil_opt -b flux -d s3 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil_opt -b flux -d s4 -t flux -i 1
srun run.py -s my_benchmarks -a 5p-stencil_opt -b flux -d s5 -t flux -i 1
srun run.py -s my_benchmarks -a kmeans -b flux -d s1 -t flux -i 1
srun run.py -s my_benchmarks -a kmeans -b flux -d s2 -t flux -i 1
srun run.py -s my_benchmarks -a kmeans -b flux -d s3 -t flux -i 1
srun run.py -s my_benchmarks -a kmeans -b flux -d s4 s5 -t flux -i 1
srun run.py -s my_benchmarks -a 2DConvolution -b flux -d s1 -t flux -i 1
srun run.py -s my_benchmarks -a 2DConvolution -b flux -d s2 -t flux -i 1
srun run.py -s my_benchmarks -a 2DConvolution -b flux -d s3 -t flux -i 1
srun run.py -s my_benchmarks -a 2DConvolution -b flux -d s4 -t flux -i 1
srun run.py -s my_benchmarks -a 2DConvolution -b flux -d s5 -t flux -i 1
srun run.py -s my_benchmarks -a atax -b flux -d s1 -t flux -i 1
srun run.py -s my_benchmarks -a atax -b flux -d s2 -t flux -i 1
srun run.py -s my_benchmarks -a atax -b flux -d s3 -t flux -i 1
srun run.py -s my_benchmarks -a atax -b flux -d s4 -t flux -i 1
srun run.py -s my_benchmarks -a gemm -b flux -d s1 -t flux -i 1
srun run.py -s my_benchmarks -a gemm -b flux -d s2 -t flux -i 1
srun run.py -s my_benchmarks -a gemm -b flux -d s3 -t flux -i 1
srun run.py -s my_benchmarks -a gemm -b flux -d s4 -t flux -i 1
srun run.py -s my_benchmarks -a mvt -b flux -d s1 -t flux -i 1
srun run.py -s my_benchmarks -a mvt -b flux -d s2 -t flux -i 1
srun run.py -s my_benchmarks -a mvt -b flux -d s3 -t flux -i 1
srun run.py -s my_benchmarks -a mvt -b flux -d s4 -t flux -i 1
